-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'NEW_RESERVATION';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'STAFF_ASSIGNED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CHECKLIST_REMINDER';
