import { StyleSheet } from "react-native";
import { COLORS } from "@/constants/colors";

export const extrasStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  card: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    padding: 20,
    paddingBottom: 32,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  title: { fontSize: 17, fontWeight: "800", color: COLORS.textPrimary },
  subtitle: { fontSize: 13, color: COLORS.textTertiary, marginBottom: 16 },
  priceInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.bgSection,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 4,
  },
  priceSymbol: {
    fontSize: 26,
    fontWeight: "800",
    color: COLORS.textTertiary,
  },
  priceInput: {
    flex: 1,
    fontSize: 26,
    fontWeight: "800",
    color: COLORS.textPrimary,
  },
  actions: { flexDirection: "row", gap: 10, marginTop: 20 },
  cancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: COLORS.bgSection,
    alignItems: "center",
  },
  cancelBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.textTertiary,
  },
  saveBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    alignItems: "center",
  },
  saveBtnText: { fontSize: 14, fontWeight: "700", color: COLORS.white },
});

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgPage },
  content: { padding: 16, paddingBottom: 40, gap: 16 },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: COLORS.bgPage,
  },
  emptyText: { fontSize: 13, color: COLORS.textDisabled },
  hero: {
    flexDirection: "row",
    gap: 14,
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 14,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  heroPhoto: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: COLORS.primaryLight,
  },
  heroPhotoPlaceholder: {
    alignItems: "center",
    justifyContent: "center",
  },
  heroInfo: { flex: 1, gap: 6 },
  petName: {
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.textPrimary,
    letterSpacing: -0.3,
  },
  heroTags: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  variantPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  variantPillText: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.primary,
  },
  doneBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: COLORS.successBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  doneText: {
    fontSize: 11,
    color: COLORS.successText,
    fontWeight: "800",
  },
  pendingBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: COLORS.infoBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  pendingText: {
    fontSize: 11,
    color: COLORS.infoText,
    fontWeight: "800",
  },
  awaitingBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: COLORS.warningBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  awaitingText: {
    fontSize: 11,
    color: COLORS.warningText,
    fontWeight: "800",
  },
  stayBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: COLORS.warningBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  stayBadgeText: {
    fontSize: 11,
    color: COLORS.warningText,
    fontWeight: "800",
  },
  section: { gap: 8 },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.textTertiary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginLeft: 4,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 14,
    gap: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  summaryCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  summaryAppointment: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingBottom: 14,
  },
  summaryAppointmentIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primaryLight,
    alignItems: "center",
    justifyContent: "center",
  },
  summaryAppointmentDate: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.textPrimary,
    textTransform: "capitalize",
    letterSpacing: -0.2,
  },
  summaryAppointmentTime: {
    fontSize: 12,
    color: COLORS.textTertiary,
    fontWeight: "600",
    marginTop: 2,
  },
  summaryDivider: {
    height: 1,
    backgroundColor: COLORS.bgSection,
    marginHorizontal: -16,
  },
  summaryGrid: {
    flexDirection: "row",
    paddingVertical: 14,
  },
  summaryCol: {
    flex: 1,
    gap: 3,
  },
  summaryColDivider: {
    width: 1,
    backgroundColor: COLORS.bgSection,
    marginHorizontal: 14,
  },
  summaryColLabel: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    color: COLORS.textTertiary,
    textTransform: "uppercase",
  },
  summaryColValue: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.textPrimary,
    marginTop: 4,
  },
  summaryColSub: {
    fontSize: 12,
    color: COLORS.textTertiary,
    fontWeight: "600",
  },
  summaryCallLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
    alignSelf: "flex-start",
  },
  summaryCallLinkText: {
    fontSize: 12,
    color: COLORS.primary,
    fontWeight: "800",
  },
  summaryNotes: {
    flexDirection: "row",
    gap: 8,
    backgroundColor: COLORS.notesBg,
    padding: 10,
    borderRadius: 10,
    marginBottom: 14,
  },
  summaryPayRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 14,
  },
  summaryTotal: {
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.primary,
    letterSpacing: -0.5,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 10 },
  rowText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.textPrimary,
  },
  notes: {
    flexDirection: "row",
    gap: 8,
    backgroundColor: COLORS.notesBg,
    padding: 10,
    borderRadius: 10,
  },
  notesText: { flex: 1, fontSize: 13, color: COLORS.notesText },
  callBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: COLORS.primaryLight,
    paddingVertical: 10,
    borderRadius: 10,
    marginTop: 4,
  },
  callBtnText: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: "800",
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  totalLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.textTertiary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  totalAmount: {
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.primary,
  },
  paymentNote: {
    fontSize: 12,
    color: COLORS.textTertiary,
    fontWeight: "600",
  },
  completeBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    borderRadius: 12,
  },
  completeBtnDisabled: { opacity: 0.7 },
  completeText: { color: COLORS.white, fontSize: 15, fontWeight: "800" },
  manualPaySection: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: COLORS.warningText,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  manualPayHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  manualPayTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.warningText,
  },
  manualPayTotal: {
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.warningText,
  },
  manualPayBreakdown: {
    gap: 4,
    paddingLeft: 26,
  },
  manualPayBreakdownText: {
    fontSize: 12,
    color: COLORS.textTertiary,
    fontWeight: "600",
  },
  // Botón "Registrar pago manual" estilo admin (dashed border).
  registerPaymentBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    borderStyle: "dashed",
    backgroundColor: COLORS.primaryLight,
  },
  registerPaymentText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.primary,
  },
  // Modal de pago manual (idéntico al admin).
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalKav: {
    width: "100%",
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 32,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textSecondary,
    marginBottom: 6,
    marginTop: 10,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: COLORS.textPrimary,
    textAlignVertical: "top",
  },
  methodRow: {
    flexDirection: "row",
    gap: 10,
  },
  methodChip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: COLORS.bgSection,
  },
  methodChipActive: {
    backgroundColor: COLORS.primary,
  },
  methodChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textTertiary,
  },
  modalButtons: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  modalBtnCancel: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    backgroundColor: COLORS.bgSection,
    alignItems: "center",
  },
  modalBtnCancelText: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.textTertiary,
  },
  modalBtnConfirm: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    alignItems: "center",
  },
  modalBtnConfirmText: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.white,
  },
  extrasSetBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: COLORS.primaryLight,
    paddingVertical: 10,
    borderRadius: 10,
  },
  extrasSetBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.primary,
  },
  extrasStatusPaid: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    backgroundColor: COLORS.successBg,
    paddingVertical: 9,
    borderRadius: 10,
  },
  extrasStatusPaidText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.successText,
  },
  extrasPickupBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: COLORS.warningBg,
    paddingVertical: 10,
    borderRadius: 10,
  },
  extrasPickupBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.warningText,
  },
  breakdown: {
    backgroundColor: COLORS.bgSection,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 8,
    marginBottom: 10,
  },
  breakdownRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  breakdownLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textSecondary,
  },
  breakdownAmount: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  breakdownDivider: {
    height: 1,
    backgroundColor: COLORS.borderLight,
  },
  breakdownTotalLabel: {
    color: COLORS.textPrimary,
    fontWeight: "800",
  },
  breakdownTotalAmount: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: "800",
  },
  extraSetChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.successBg,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  extraSetChipLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.successText,
  },
  extraSetChipPrice: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.successText,
  },
  extrasPending: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    backgroundColor: COLORS.infoBg,
    paddingVertical: 9,
    borderRadius: 10,
  },
  extrasPendingText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.infoText,
  },
  // Foto del baño + visor fullscreen
  photoGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  addPhotoTile: {
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  addPhotoTileText: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.primary,
  },
  photoThumbWrap: {
    position: "relative",
    width: 96,
    height: 96,
    borderRadius: 10,
    overflow: "hidden",
  },
  photoThumb: {
    width: "100%",
    height: "100%",
    backgroundColor: COLORS.bgSection,
  },
  photoExpandBadge: {
    position: "absolute",
    right: 6,
    bottom: 6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "rgba(0,0,0,0.55)",
    alignItems: "center",
    justifyContent: "center",
  },
  fullscreenBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.95)",
    alignItems: "center",
    justifyContent: "center",
  },
  fullscreenImage: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    width: undefined,
    height: undefined,
  },
  fullscreenClose: {
    position: "absolute",
    top: 56,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
});
