import { StyleSheet } from "react-native";
import { COLORS } from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgPage },
  contentContainer: { padding: 16, paddingBottom: 40 },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.bgPage,
  },
  emptyText: { fontSize: 14, color: COLORS.textDisabled },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    gap: 8,
  },
  headerLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minWidth: 0,
  },
  petAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: COLORS.bgSection,
  },
  petAvatarFallback: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.primaryLight,
  },
  petName: {
    flex: 1,
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.textPrimary,
  },
  badge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20 },
  badgeText: { fontSize: 13, fontWeight: "700" },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  cardTitle: { fontSize: 16, fontWeight: "800", color: COLORS.textPrimary },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  infoLeft: { flexDirection: "row", alignItems: "center", gap: 8 },
  infoLabel: { fontSize: 14, color: COLORS.textTertiary },
  infoValue: { fontSize: 14, fontWeight: "600", color: COLORS.textPrimary },
  // Date hero
  dateHero: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
  },
  datePill: {
    flex: 1,
    backgroundColor: COLORS.bgSection,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 10,
    alignItems: "center",
  },
  datePillLabel: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.6,
    color: COLORS.textTertiary,
    marginBottom: 4,
  },
  datePillDay: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.textPrimary,
    textTransform: "capitalize",
  },
  datePillSub: {
    fontSize: 11,
    color: COLORS.textTertiary,
    textTransform: "capitalize",
    marginTop: 2,
  },
  dateConnector: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  connectorLine: {
    flex: 1,
    width: 1,
    backgroundColor: COLORS.borderLight,
    minHeight: 8,
  },
  nightsBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    marginVertical: 4,
  },
  nightsBadgeText: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.primary,
  },
  // Bath hero
  bathHero: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: COLORS.bgSection,
    borderRadius: 12,
    padding: 12,
  },
  bathBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  bathBadgeText: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.primary,
  },
  bathInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  bathDay: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.textPrimary,
    textTransform: "capitalize",
  },
  bathTime: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.textTertiary,
  },
  // Meta row
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.bgSection,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 10,
    marginTop: 12,
  },
  metaItem: {
    flex: 1,
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 6,
  },
  metaIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  },
  metaLabel: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
    color: COLORS.textTertiary,
  },
  metaValue: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.textPrimary,
    textAlign: "center",
  },
  metaDivider: {
    width: 1,
    alignSelf: "stretch",
    backgroundColor: COLORS.borderLight,
    marginVertical: 4,
  },
  // Total footer
  totalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: COLORS.bgSection,
    paddingTop: 12,
    marginTop: 12,
  },
  totalLabel: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.textTertiary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  totalAmount: {
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.primary,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: COLORS.bgSection,
    paddingTop: 10,
    marginTop: 4,
  },
  totalValue: { fontSize: 20, fontWeight: "800", color: COLORS.primary },
  // Payments card
  sectionCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  countChip: {
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    minWidth: 22,
    alignItems: "center",
  },
  countChipText: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.primary,
  },
  paymentIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.primaryLight,
    alignItems: "center",
    justifyContent: "center",
  },
  paymentRowNew: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.bgSection,
  },
  paymentRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  paymentAmount: {
    fontSize: 16,
    fontWeight: "800",
    color: COLORS.textPrimary,
  },
  paymentMeta: {
    fontSize: 11,
    color: COLORS.textTertiary,
    marginTop: 2,
  },
  paymentBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  paymentBadgeText: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  paymentRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  paymentRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  refundPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.successBg,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 12,
    borderWidth: 1,
    borderColor: COLORS.successText,
  },
  refundPillText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.successText,
  },
  refundBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  refundBannerTitle: {
    color: COLORS.white,
    fontWeight: "800",
    fontSize: 15,
  },
  refundBannerSub: {
    color: COLORS.white,
    opacity: 0.9,
    fontSize: 12,
    marginTop: 2,
  },
  pendingBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: COLORS.warningBg,
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  pendingBannerText: { flex: 1, gap: 2 },
  pendingBannerTitle: { fontSize: 14, fontWeight: "700", color: COLORS.warningText },
  pendingBannerBody: { fontSize: 13, color: COLORS.warningText, lineHeight: 18, opacity: 0.85 },
  notesCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: COLORS.notesBg,
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
  },
  notesText: { flex: 1, fontSize: 14, color: COLORS.notesText, lineHeight: 20 },
  reviewCard: {
    backgroundColor: COLORS.reviewBg,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.reviewBorder,
    gap: 8,
  },
  reviewTitle: { fontSize: 16, fontWeight: "700", color: COLORS.primary },
  pawRow: { flexDirection: "row", gap: 4 },
  reviewComment: {
    fontSize: 14,
    color: COLORS.textTertiary,
    lineHeight: 20,
    marginTop: 4,
  },
  reviewCTA: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: COLORS.reviewBg,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.reviewBorder,
  },
  reviewCTAText: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.primary,
  },
  // Group pets
  groupPetRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 6,
  },
  groupPetName: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.textPrimary,
  },
  groupPetBreed: {
    fontSize: 13,
    color: COLORS.textTertiary,
    flex: 1,
  },
  groupPetAmount: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.primary,
  },
  groupTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: COLORS.bgSection,
    paddingTop: 8,
    marginTop: 4,
  },
  groupTotalLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  groupTotalValue: {
    fontSize: 16,
    fontWeight: "800",
    color: COLORS.primary,
  },
  // Balance banner
  balanceBanner: {
    backgroundColor: COLORS.warningBg,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.warningText,
    gap: 8,
  },
  balanceBannerHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  balanceBannerTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.warningText,
  },
  balanceBannerAmount: {
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.textPrimary,
  },
  balanceBannerDeadline: {
    fontSize: 14,
    color: COLORS.textSecondary,
  },
  balanceBannerWarning: {
    fontSize: 13,
    color: COLORS.warningText,
    lineHeight: 18,
  },
  balanceButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: COLORS.primary,
    borderRadius: 10,
    paddingVertical: 14,
    marginTop: 4,
  },
  balanceButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.white,
  },
  actionsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  secondaryButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  secondaryButtonText: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: "700",
  },
  dangerButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.errorText,
  },
  dangerButtonText: {
    color: COLORS.errorText,
    fontSize: 14,
    fontWeight: "700",
  },
  pendingChangeBanner: {
    backgroundColor: COLORS.warningBg,
    borderWidth: 1,
    borderColor: COLORS.warningText,
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
  },
  pendingChangeHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 6,
  },
  pendingChangeTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.warningText,
  },
  pendingChangeBody: {
    fontSize: 13,
    color: COLORS.textPrimary,
    fontWeight: "600",
  },
  pendingChangeSubtitle: {
    fontSize: 12,
    color: COLORS.textTertiary,
    marginTop: 4,
  },
  checklistsCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 14,
    marginTop: 12,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  checklistsIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primaryLight,
    alignItems: "center",
    justifyContent: "center",
  },
  checklistsTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  checklistsSubtitle: {
    fontSize: 13,
    color: COLORS.textTertiary,
    marginTop: 2,
  },
  // Bath services card (deslanado/corte + nota de cobro post-servicio)
  bathServicesCard: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.primaryLight,
    gap: 12,
  },
  bathServicesHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  bathServicesIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.primaryLight,
    alignItems: "center",
    justifyContent: "center",
  },
  bathServicesTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.textPrimary,
  },
  bathServicesChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  bathServiceChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
  },
  bathServiceChipText: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.primary,
  },
  bathServicesNoteBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: COLORS.infoBg,
    borderRadius: 10,
    padding: 10,
  },
  bathServicesNoteText: {
    flex: 1,
    fontSize: 12,
    color: COLORS.infoText,
    lineHeight: 17,
    fontWeight: "600",
  },
  bathServicesCardPaid: {
    borderColor: COLORS.successText,
    backgroundColor: COLORS.successBg,
  },
  bathServicesPaidPill: {
    backgroundColor: COLORS.successText,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  bathServicesPaidPillText: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.white,
    letterSpacing: 0.3,
  },
  bathServicesItemized: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  bathServicesRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.bgSection,
  },
  bathServicesRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  bathServicesRowLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.textPrimary,
  },
  bathServicesRowValue: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  bathServicesTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 10,
    paddingBottom: 4,
  },
  bathServicesTotalLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.textTertiary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  bathServicesTotalValue: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.successText,
  },
});
