import { StyleSheet } from "react-native";
import { COLORS } from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bgPage },
  contentContainer: { padding: 16, paddingBottom: 40 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    gap: 12,
  },
  title: { fontSize: 24, fontWeight: "800", color: COLORS.textPrimary },
  pendingBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: COLORS.warningBg,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.warningText,
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  pendingBannerTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.warningText,
    marginBottom: 2,
  },
  pendingBannerBody: {
    fontSize: 12,
    color: COLORS.textSecondary,
    lineHeight: 16,
  },
  section: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
    gap: 12,
  },
  sectionTitle: { fontSize: 16, fontWeight: "700", color: COLORS.textPrimary },
  hint: { fontSize: 13, color: COLORS.textTertiary, marginTop: -8 },
  label: { fontSize: 13, fontWeight: "600", color: COLORS.textTertiary, marginBottom: 4 },
  dateRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  dateCol: { flex: 1 },
  dateButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: COLORS.white,
  },
  dateText: { fontSize: 15, color: COLORS.textPrimary },
  nightsText: { fontSize: 14, fontWeight: "600", color: COLORS.primary, textAlign: "center" },
  datePickersRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 8,
  },
  // Pets
  petSectionHighlight: {
    borderWidth: 2,
    borderColor: COLORS.primary,
    shadowOpacity: 0.12,
  },
  petTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  requiredAsterisk: {
    color: COLORS.errorText,
    fontWeight: "800",
  },
  petCountBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.primary,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  petCountBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.white,
  },
  petCueBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.primaryLight,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: -4,
  },
  petCueBannerText: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.primary,
  },
  petRow: { flexDirection: "row", gap: 12, paddingVertical: 4 },
  petChip: {
    alignItems: "center",
    borderWidth: 2,
    borderColor: COLORS.borderLight,
    borderRadius: 14,
    padding: 12,
    width: 110,
    position: "relative",
  },
  petChipSelected: { borderColor: COLORS.primary, backgroundColor: COLORS.primary },
  petCheckmark: { position: "absolute", top: 6, right: 6, zIndex: 1 },
  cartillaLock: {
    position: "absolute",
    top: 6,
    right: 6,
    zIndex: 1,
    backgroundColor: COLORS.warningText,
    borderRadius: 10,
    padding: 3,
  },
  cartillaChipWarn: {
    fontSize: 10,
    fontWeight: "700",
    color: COLORS.warningText,
    textAlign: "center",
    marginTop: 4,
  },
  petChipPhoto: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginBottom: 6,
    backgroundColor: COLORS.bgSection,
  },
  petChipName: { fontSize: 14, fontWeight: "700", color: COLORS.textPrimary },
  petChipNameSelected: { color: COLORS.white },
  petChipWeight: { fontSize: 12, color: COLORS.textTertiary, marginTop: 2 },
  emptyBox: { alignItems: "center", gap: 8, padding: 12 },
  emptyText: { fontSize: 14, color: COLORS.textDisabled, textAlign: "center" },
  linkButton: { flexDirection: "row", alignItems: "center", gap: 6 },
  linkText: { fontSize: 14, fontWeight: "600", color: COLORS.primary },
  // Room preference
  prefRow: { flexDirection: "row", gap: 10 },
  prefButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: 12,
    paddingVertical: 14,
  },
  prefButtonSelected: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  prefText: { fontSize: 14, fontWeight: "600", color: COLORS.textTertiary },
  prefTextSelected: { color: COLORS.white },
  // Price
  priceCard: {
    backgroundColor: COLORS.primaryLight,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.primary,
    gap: 8,
  },
  priceTitle: { fontSize: 16, fontWeight: "700", color: COLORS.primary },
  priceRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  priceLabel: { fontSize: 14, color: COLORS.textTertiary },
  priceValue: { fontSize: 14, fontWeight: "600", color: COLORS.textSecondary },
  discountRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 4 },
  discountInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    color: COLORS.textPrimary,
    backgroundColor: COLORS.white,
  },
  discountApplyBtn: {
    height: 40,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  discountApplyBtnDisabled: { opacity: 0.5 },
  discountApplyText: { color: COLORS.primary, fontWeight: "700", fontSize: 14 },
  discountAppliedValue: { flexDirection: "row", alignItems: "center", gap: 8 },
  discountValueText: { fontSize: 14, fontWeight: "700", color: COLORS.successText },
  priceTotalRow: {
    borderTopWidth: 1,
    borderTopColor: COLORS.primary,
    paddingTop: 8,
    marginTop: 4,
  },
  priceTotalLabel: { fontSize: 16, fontWeight: "700", color: COLORS.primary },
  priceTotalValue: { fontSize: 20, fontWeight: "800", color: COLORS.primary },
  // Legal
  checkRow: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  checkText: { fontSize: 14, color: COLORS.textSecondary, flex: 1, lineHeight: 20 },
  checkLink: { color: COLORS.primary, fontWeight: "600", textDecorationLine: "underline" },
  // Notes
  input: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: COLORS.textPrimary,
  },
  multiline: { minHeight: 80, textAlignVertical: "top" },
  // Submit
  submitButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    paddingVertical: 16,
    marginTop: 8,
  },
  submitText: { fontSize: 17, fontWeight: "700", color: COLORS.white },
  // Deposit
  depositDisabledHint: { fontSize: 12, color: COLORS.textDisabled, marginTop: -4 },
  depositInfo: { gap: 6, marginTop: 4 },
  depositCharge: { fontSize: 15, fontWeight: "700", color: COLORS.successText },
  depositRemaining: { fontSize: 14, color: COLORS.textTertiary },
  depositWarning: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    backgroundColor: COLORS.warningBg,
    borderRadius: 8,
    padding: 10,
    marginTop: 4,
  },
  depositWarningText: {
    fontSize: 13,
    color: COLORS.warningText,
    flex: 1,
    lineHeight: 18,
  },
  surchargeWarning: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: COLORS.warningBg,
    borderRadius: 8,
    padding: 12,
    marginTop: 4,
  },
  surchargeWarningText: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.warningText,
    flex: 1,
    lineHeight: 18,
  },
  medicationNotesWrap: {
    paddingLeft: 32,
    gap: 6,
  },
  medicationNotesError: {
    flex: 1,
    fontSize: 12,
    color: COLORS.errorText,
    fontWeight: "600",
  },
  medicationErrorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  availabilityBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    backgroundColor: COLORS.errorBg,
    borderWidth: 1,
    borderColor: COLORS.errorText,
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
  },
  availabilityTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.errorText,
  },
  availabilityBody: {
    fontSize: 13,
    color: COLORS.errorText,
    marginTop: 2,
    lineHeight: 18,
  },
  // Bath upsell
  bathPetBlock: {
    borderTopWidth: 1,
    borderTopColor: COLORS.bgSection,
    paddingTop: 10,
    gap: 8,
  },
  bathToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  bathPetName: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.textPrimary,
  },
  bathPrice: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.primary,
  },
  bathOptionsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
    paddingLeft: 34,
    flexWrap: "wrap",
  },
  bathChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: COLORS.borderLight,
    backgroundColor: COLORS.white,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
    elevation: 1,
  },
  bathChipSelected: {
    backgroundColor: COLORS.primaryLight,
    borderColor: COLORS.primary,
  },
  bathChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textSecondary,
    letterSpacing: 0.2,
  },
  bathChipTextSelected: {
    color: COLORS.primary,
    fontWeight: "700",
  },
  bathExtrasNote: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 6,
    marginTop: 6,
    padding: 10,
    backgroundColor: COLORS.warningBg,
    borderRadius: 8,
  },
  bathExtrasNoteText: {
    flex: 1,
    fontSize: 12,
    color: COLORS.warningText,
    fontWeight: "600",
    lineHeight: 17,
  },
  creditHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingTop: 10,
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: COLORS.bgSection,
  },
  creditHintText: {
    flex: 1,
    fontSize: 12,
    color: COLORS.successText,
    fontWeight: "600",
  },
  totalWithCredit: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
  },
  priceTotalStrike: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textDisabled,
    textDecorationLine: "line-through",
  },
  deliveryQuoteRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: COLORS.primaryLight,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  deliveryQuoteText: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.primary,
  },
});
