import { StyleSheet } from "react-native";
import { COLORS } from "@/constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bgPage,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.bgPage,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: 12,
  },
  headerInfo: {
    flex: 1,
  },
  petName: {
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.textPrimary,
  },
  ownerName: {
    fontSize: 14,
    color: COLORS.textTertiary,
    marginTop: 2,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  statusText: {
    fontSize: 12,
    fontWeight: "700",
  },
  card: {
    backgroundColor: COLORS.white,
    marginHorizontal: 16,
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  petProfileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 12,
  },
  editPetButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  editPetButtonText: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.primary,
  },
  petPhoto: {
    width: 70,
    height: 70,
    borderRadius: 14,
  },
  petPhotoPlaceholder: {
    backgroundColor: COLORS.bgSection,
    alignItems: "center",
    justifyContent: "center",
  },
  petDetails: {
    flex: 1,
    justifyContent: "center",
  },
  petBreed: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  petDetail: {
    fontSize: 14,
    color: COLORS.textTertiary,
    marginTop: 2,
  },
  notesBox: {
    flexDirection: "row",
    gap: 8,
    backgroundColor: COLORS.bgPage,
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
  },
  notesText: {
    flex: 1,
    fontSize: 13,
    color: COLORS.textTertiary,
    lineHeight: 18,
  },
  bathRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.bgSection,
  },
  bathLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  bathDetail: {
    flex: 1,
    fontSize: 13,
    color: COLORS.textTertiary,
  },
  bathPrice: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.primary,
  },
  vaccinesSection: {
    marginTop: 4,
    marginBottom: 12,
  },
  subsectionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.textSecondary,
    marginBottom: 8,
  },
  vaccineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 4,
  },
  vaccineName: {
    flex: 1,
    fontSize: 13,
    color: COLORS.textSecondary,
  },
  vaccineDate: {
    fontSize: 12,
  },
  stayInfoRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.bgSection,
  },
  // Saldo pendiente — card propia
  payCard: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 16,
    backgroundColor: COLORS.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.warningText,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  payHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  payTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.warningText,
  },
  payTotal: {
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.warningText,
  },
  payBreakdown: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.bgSection,
    gap: 6,
  },
  payRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  payRowLabel: {
    fontSize: 13,
    color: COLORS.textTertiary,
    fontWeight: "600",
  },
  payRowValue: {
    fontSize: 13,
    color: COLORS.textPrimary,
    fontWeight: "700",
  },
  payRowValueDiscount: {
    fontSize: 13,
    color: COLORS.successText,
    fontWeight: "700",
  },
  registerPaymentBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 12,
    paddingVertical: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    borderStyle: "dashed",
    backgroundColor: COLORS.primaryLight,
  },
  registerPaymentText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.primary,
  },
  // Modal pago manual
  modalKav: {
    width: "100%",
  },
  payModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  payModalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 32,
  },
  payModalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 16,
  },
  payInputLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textSecondary,
    marginBottom: 6,
    marginTop: 10,
  },
  payModalInput: {
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: COLORS.textPrimary,
    textAlignVertical: "top",
  },
  payMethodRow: {
    flexDirection: "row",
    gap: 10,
  },
  payMethodChip: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: COLORS.bgSection,
  },
  payMethodChipActive: {
    backgroundColor: COLORS.primary,
  },
  payMethodChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textTertiary,
  },
  payModalButtons: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  payModalBtnCancel: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    backgroundColor: COLORS.bgSection,
    alignItems: "center",
  },
  payModalBtnCancelText: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.textTertiary,
  },
  payModalBtnConfirm: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    backgroundColor: COLORS.primary,
    alignItems: "center",
  },
  payModalBtnConfirmText: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.white,
  },
  stayInfoItem: {
    alignItems: "center",
  },
  stayInfoLabel: {
    fontSize: 11,
    color: COLORS.textDisabled,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  stayInfoValue: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginTop: 2,
  },
  // Hora estimada indicada por el cliente (bajo la fecha de entrada/salida).
  stayInfoTime: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.primary,
    marginTop: 1,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginHorizontal: 16,
    marginTop: 16,
    padding: 14,
    borderRadius: 12,
  },
  actionButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "700",
  },
  actionsRow: {
    flexDirection: "row",
    gap: 12,
    marginHorizontal: 16,
    marginTop: 16,
  },
  pickupChargeBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: COLORS.warningBg,
    borderWidth: 1,
    borderColor: COLORS.warningText,
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 16,
    marginTop: 16,
  },
  pickupChargeBtnText: {
    color: COLORS.warningText,
    fontSize: 14,
    fontWeight: "700",
  },
  actionButtonSmall: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: 12,
    borderRadius: 12,
  },
  actionButtonSmallText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: "700",
  },
  section: {
    marginHorizontal: 16,
    marginTop: 20,
  },
  sideBySideRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    paddingHorizontal: 16,
  },
  sideCol: {
    flex: 1,
    marginHorizontal: 0,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  emptyText: {
    fontSize: 13,
    color: COLORS.textDisabled,
    textAlign: "center",
    paddingVertical: 12,
  },
  evidenceItem: {
    marginRight: 10,
  },
  evidenceImageWrap: {
    width: 100,
    height: 100,
    position: "relative",
  },
  evidenceImage: {
    width: 100,
    height: 100,
    borderRadius: 10,
    backgroundColor: COLORS.bgSection,
  },
  evidencePlayOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.18)",
    borderRadius: 10,
  },
  evidenceCaption: {
    fontSize: 11,
    color: COLORS.textTertiary,
    marginTop: 4,
    width: 100,
  },
  tagsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  alertRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
  },
  alertType: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.textSecondary,
  },
  alertDesc: {
    fontSize: 13,
    color: COLORS.textTertiary,
    marginTop: 2,
  },
  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: "60%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  roomValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  roomRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.borderLight,
  },
  roomRowName: { fontSize: 15, fontWeight: "600", color: COLORS.textPrimary },
  roomRowSub: { fontSize: 12, color: COLORS.textTertiary, marginTop: 2 },
  roomRowCurrent: { fontSize: 12, fontWeight: "700", color: COLORS.primary },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  modalDescription: {
    fontSize: 13,
    color: COLORS.textTertiary,
    lineHeight: 18,
    marginBottom: 16,
  },
  alertTypeChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: COLORS.bgSection,
    marginRight: 8,
  },
  alertTypeChipActive: {
    backgroundColor: COLORS.warningText,
  },
  alertTypeChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textTertiary,
  },
  textArea: {
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: COLORS.textPrimary,
    minHeight: 110,
    textAlignVertical: "top",
    backgroundColor: COLORS.white,
  },
  modalButtons: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  modalButtonCancel: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    backgroundColor: COLORS.bgSection,
    alignItems: "center",
  },
  modalButtonCancelText: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.textTertiary,
  },
  modalButtonConfirm: {
    flex: 1,
    padding: 14,
    borderRadius: 10,
    backgroundColor: COLORS.warningText,
    alignItems: "center",
  },
  modalButtonConfirmText: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.white,
  },
  tagsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 16,
  },
  tagOption: {
    padding: 4,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: "transparent",
  },
  tagOptionSelected: {
    borderColor: COLORS.primary,
  },
  tagNotesLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.textSecondary,
    marginBottom: 6,
  },
  // Owner strip (within pet card)
  ownerStrip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  ownerStripName: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  ownerStripContact: {
    fontSize: 12,
    color: COLORS.textTertiary,
    marginTop: 1,
  },
  cardDivider: {
    height: 1,
    backgroundColor: COLORS.bgSection,
    marginVertical: 12,
  },
  medicationBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: COLORS.errorBg,
    padding: 10,
    borderRadius: 8,
    marginTop: 10,
  },
  medicationTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.errorText,
  },
  medicationNotes: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginTop: 2,
    lineHeight: 18,
  },
  // Bath section
  bathSection: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.bgSection,
  },
  completeBathButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: COLORS.successText,
    paddingVertical: 8,
    borderRadius: 8,
    marginTop: 8,
  },
  completeBathText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.white,
  },
  bathCompletedDate: {
    fontSize: 12,
    color: COLORS.successText,
    marginTop: 6,
    fontStyle: "italic",
  },
  // Resolve alert button
  resolveButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.successBg,
    alignItems: "center",
    justifyContent: "center",
  },
  // Evidence date
  evidenceDate: {
    fontSize: 10,
    color: COLORS.textDisabled,
    marginTop: 3,
  },
  missingReportBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.warningBg,
    padding: 12,
    borderRadius: 10,
    marginTop: 8,
  },
  missingReportText: {
    flex: 1,
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.warningText,
  },
  checklistsCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 14,
    marginHorizontal: 16,
    marginTop: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  checklistsIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primaryLight,
    alignItems: "center",
    justifyContent: "center",
  },
  checklistsTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  checklistsSubtitle: {
    fontSize: 13,
    color: COLORS.textTertiary,
    marginTop: 2,
  },
});
