// Catálogo local de razas de perro (es-MX) para el autocompletado del alta de
// mascota. NO es una restricción: el campo "Raza" sigue siendo texto libre; esta
// lista solo sugiere. Incluye las más frecuentes en México y opciones para
// mezclas ("Mestizo", "Criollo") y la raza mexicana "Xoloitzcuintle".

export const DOG_BREEDS: string[] = [
  "Mestizo",
  "Criollo",
  "Affenpinscher",
  "Airedale Terrier",
  "Akita Americano",
  "Akita Inu",
  "Alaskan Malamute",
  "American Bully",
  "American Staffordshire Terrier",
  "Basenji",
  "Basset Hound",
  "Beagle",
  "Bedlington Terrier",
  "Bichón Frisé",
  "Bichón Habanero",
  "Bichón Maltés",
  "Bloodhound",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Bóxer",
  "Boyero de Berna",
  "Boyero de Australia",
  "Braco Alemán",
  "Braco de Weimar",
  "Braco Húngaro",
  "Bulldog Americano",
  "Bulldog Francés",
  "Bulldog Inglés",
  "Bullmastiff",
  "Bull Terrier",
  "Cairn Terrier",
  "Cane Corso",
  "Caniche",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chow Chow",
  "Cocker Spaniel Americano",
  "Cocker Spaniel Inglés",
  "Collie",
  "Corgi Galés de Pembroke",
  "Coton de Tulear",
  "Crestado Chino",
  "Dálmata",
  "Dóberman",
  "Dogo Argentino",
  "Dogo de Burdeos",
  "Dogue de Burdeos",
  "Fila Brasileño",
  "Fox Terrier",
  "Galgo Afgano",
  "Galgo Español",
  "Galgo Inglés",
  "Golden Retriever",
  "Gran Danés",
  "Gran Pirineo",
  "Husky Siberiano",
  "Jack Russell Terrier",
  "Keeshond",
  "Kelpie Australiano",
  "Labrador Retriever",
  "Lagotto Romagnolo",
  "Lebrel Irlandés",
  "Leonberger",
  "Lhasa Apso",
  "Maltés",
  "Mastín Español",
  "Mastín Inglés",
  "Mastín Napolitano",
  "Mastín Tibetano",
  "Pastor Alemán",
  "Pastor Australiano",
  "Pastor Belga Malinois",
  "Pastor Blanco Suizo",
  "Pastor Caucásico",
  "Pastor de Shetland",
  "Pastor Ganadero Australiano",
  "Pekinés",
  "Perro de Agua Español",
  "Perro de Agua Portugués",
  "Perro Sin Pelo del Perú",
  "Pinscher Miniatura",
  "Pit Bull",
  "Pointer Inglés",
  "Pomerania",
  "Poodle",
  "Presa Canario",
  "Pug",
  "Rottweiler",
  "Rhodesian Ridgeback",
  "Salchicha (Dachshund)",
  "Samoyedo",
  "San Bernardo",
  "Schnauzer Estándar",
  "Schnauzer Gigante",
  "Schnauzer Miniatura",
  "Setter Irlandés",
  "Setter Inglés",
  "Shar Pei",
  "Shiba Inu",
  "Shih Tzu",
  "Spitz Alemán",
  "Spitz Japonés",
  "Staffordshire Bull Terrier",
  "Terranova",
  "Terrier Escocés",
  "Terrier Ruso Negro",
  "Vizsla",
  "Weimaraner",
  "West Highland White Terrier",
  "Whippet",
  "Xoloitzcuintle",
  "Yorkshire Terrier",
];

// Otros nombres con los que alguien puede buscar una raza. La sugerencia que se
// muestra (y se guarda) es siempre la del catálogo: "Teckel" era el nombre que
// salía antes y nadie del equipo lo reconocía como el salchicha.
export const BREED_ALIASES: Record<string, string[]> = {
  "Salchicha (Dachshund)": ["Teckel", "Perro Salchicha"],
};

// Normaliza para comparar sin acentos ni mayúsculas.
export function normalizeBreed(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "") // quita acentos (marcas diacríticas)
    .trim();
}
